Implement frequency analysis
kristina71/avito_otus pull request #3
Opened 2022-05-25 08:53 UTC by kristina71

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ да] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ да] Я запустил `go mod tidy`.
- [ да] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-05-25 15:10 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако есть критичные замечания в логике функции, поэтому возвращаю на доработку

Итого: 5 баллов из 10

2022-05-25 15:10 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile("[А-Яа-яA-Za-z0-9'*?()$.,!-:]+")
Рекомендую обратить внимание на [частые ошибки](https://github.com/Tiksy1/otus_hw-test/tree/hw03_frequency_analysis/hw03_frequency_analysis#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8)

2022-05-25 15:10 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		return wordsCount[list[i]] > wordsCount[list[j]]
> Если слова имеют одинаковую частоту, то должны быть отсортированы лексикографически.

Похоже, такого критерия не хватает

2022-05-25 15:10 UTC, agneum commented on hw03_frequency_analysis/top_test.go
> +			require.Len(t, Top10(text), 10)
Не совсем корректно подгонять тесты под решение - предполагается использовать `Equal`, предлагаю добавить лексикографическую сортировку.

Кстати, не хватает новых юнит-тестов

2022-06-07 21:29 UTC, kristina71 commented on hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile("[А-Яа-яA-Za-z0-9'*?()$.,!-:]+")
исправлено

2022-06-07 21:29 UTC, kristina71 commented on hw03_frequency_analysis/top.go
> +		return wordsCount[list[i]] > wordsCount[list[j]]
исправлено

2022-06-07 21:29 UTC, kristina71 commented on hw03_frequency_analysis/top_test.go
> +			require.Len(t, Top10(text), 10)
добавлено и исправлено. Мой косяк, не увидела сразу это требование

2022-06-08 02:18 UTC, agneum reviewed
Спасибо за правки. Принято.
Итого: 10 баллов из 10

2022-06-08 02:19 UTC, agneum approved these changes

2022-08-13 19:11 UTC, merged